# Generated by Django 2.0.5 on 2018-05-23 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='题目编号')),
                ('series', models.IntegerField(verbose_name='series_id')),
                ('name', models.CharField(max_length=50, verbose_name='题目名字')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='题目类型')),
                ('description', models.CharField(max_length=500, verbose_name='题目描述')),
                ('input_description', models.CharField(max_length=100, verbose_name='输入描述')),
                ('output_description', models.CharField(max_length=100, verbose_name='输出描述')),
                ('input_sample', models.CharField(max_length=100, verbose_name='输入样例')),
                ('output_sample', models.CharField(max_length=100, verbose_name='输出样例')),
                ('time', models.IntegerField(verbose_name='时间限制')),
                ('memory', models.IntegerField(verbose_name='内存限制')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
