# Generated by Django 2.0.2 on 2018-03-05 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file_name', models.CharField(max_length=50)),
                ('path', models.FilePathField()),
                ('series', models.CharField(max_length=50, verbose_name='系列')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('grade', models.CharField(max_length=50, verbose_name='年级')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
