# Generated by Django 2.0.2 on 2018-03-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculuminfo',
            options={'permissions': (('upload_file', '可以上传文件'),)},
        ),
    ]
